In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [25]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

## Evenly spaced numbers defining range and number

In [24]:
np.linspace(0, 5, 10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

## Identity Matrix

In [19]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [20]:
np.random.rand(5)

array([ 0.40794495,  0.43180941,  0.6065724 ,  0.05644225,  0.45806938])

In [23]:
np.random.rand(5,5)

array([[  1.07594705e-01,   4.82390067e-01,   9.00842351e-01,
          5.25848818e-01,   8.73574253e-01],
       [  7.64223770e-01,   7.77231748e-01,   5.45913066e-01,
          6.02534579e-01,   5.95176383e-01],
       [  6.43696301e-01,   4.10585911e-02,   6.57789109e-01,
          5.34774488e-01,   5.63994755e-01],
       [  8.30150347e-01,   7.85743048e-01,   6.15644516e-01,
          5.77061528e-01,   1.85702204e-01],
       [  2.54720750e-04,   5.71830814e-01,   4.42861667e-01,
          3.06939000e-01,   5.53871157e-01]])

## Normal Distribution

In [22]:
np.random.randn(5)

array([ 1.03675123,  0.4200773 ,  0.31094284, -0.75372273,  0.1757107 ])

In [26]:
np.random.randn(5,5)

array([[ 1.08746858, -0.16998249,  1.96846656,  1.88124075, -1.13832428],
       [-0.52789455,  0.38817981, -2.87632345,  0.59404064,  0.30004745],
       [ 0.44357194,  0.72885418, -0.28923687, -0.21871156,  1.67057548],
       [-1.08377498,  2.98670834,  0.69293278, -0.86439455, -0.65906919],
       [ 0.84378363,  1.09442276, -0.70809702, -0.74540365,  0.01247138]])

## Random integer between range (inclusive, exclusive, number)

In [28]:
np.random.randint(1, 100, 10)

array([33, 56, 66, 84, 48, 89, 58, 90, 10, 50])

In [29]:
arr = np.arange(25)

In [30]:
ranArr = np.random.randint(0, 50, 10)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranArr

array([ 7, 46, 31, 34,  0,  8, 15, 14, 47, 16])

In [33]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
ranArr.max()

47

In [36]:
ranArr.min()

0

In [37]:
ranArr.argmax()

8

In [38]:
ranArr.argmin()

4

In [39]:
arr.shape

(25,)

In [40]:
ranArr.shape

(10,)

In [41]:
arr = arr.reshape(5,5)

In [42]:
arr.shape

(5, 5)

In [ ]:
arr.